<template>
  <v-container>
    <v-layout
      text-xs-center
      wrap
    >
      <v-flex
        mb-5
        xs12
      >
        <h2 class="headline font-weight-bold mb-3">Algorithms</h2>
        <v-layout justify-center>
          <v-expansion-panel dark>
            <v-expansion-panel-content
              v-for="(problem, i) in problems"
              :key="i"
            >
              <template v-slot:header   :class='colors[i%4]'>
                <div>{{problem.title}}</div>
              </template>
              <v-card>
                <v-card-text>
                  <pre>{{problem.description}}</pre>
                </v-card-text>
              </v-card>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-layout>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>

export default {
  name: 'Algorithms',
  components: {
  },
  data: () => ({
    colors: [
      'd-blue',
      'l-blue',
      'orange',
      'yellow',
    ],
    problems: [
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Number Spiral Diagonals',
        description: 'Starting with the number 1 and moving to the r in a clockwise direction a\n5 by 5 spiral is formed as follows:\n\n       43 44 45 46 47 48 49\n       42 21 22 23 24 25 26       21 22 23 24 25 26\n       41 20  7  8  9 10 27       20  7  8  9 10 27\n       40 19  6  1  2 11 28       19  6  1  2 11 28\n       39 18  5  4  3 12 29       18  5  4  3 12 29\n       38 17 16 15 14 13 30       17 16 15 14 13 30\n       37 36 35 34 33 32 31       36 35 34 33 32 31',
      },
      {
        title: 'Digit cancelling fractions',
        description: 'The fraction 49/98 is a curious fraction, as an inexperienced mathematician in\nattempting to simplify it may incorrectly believe that 49/98 = 4/8, which is\ncorrect, is obtained by cancelling the 9s.\n\nWe shall consider fractions like, 30/50 = 3/5, to be trivial examples.\n\nThere are exactly four non-trivial examples of this type of fraction, less than\none in value, and containing two digits in the numerator and denominator.\n\nIf the product of these four fractions is given in its lowest common terms, find\nthe value of the denominator.',
      },
      {
        title: 'Truncatable primes',
        description: 'The number 3797 has an interesting property. Being prime itself, it is possible\nto continuously remove digits from left to right, and remain prime at each stage:\n  3797, 797, 97, and 7.\nSimilarly we can work from right to left:\n  3797, 379, 37, and 3.\n\nFind the sum of the only eleven primes that are both truncatable from left to\nright and right to left.\n\nNOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.',
      },
      {
        title: 'Name Scores',
        description: 'Using names.txt (right click and \'Save Link/Target As...\'), a 46K text file\ncontaining over five-thousand first names, begin by sorting it into\nalphabetical order. Then working out the alphabetical value for each name,\nmultiply this value by its alphabetical position in the list to obtain a name\nscore.\n\nFor example, when the list is sorted into alphabetical order, COLIN, which is\nworth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would\nobtain a score of 938 × 53 = 49714.\n\nWhat is the total of all the name scores in the file?',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
    ],
  }),
  mounted: {

  },
};
</script>
