<template>
  <v-container>
    <v-layout
      text-xs-center
      wrap
    >
      <v-flex
        mb-5
        xs12
      >
        <h2 class="headline font-weight-bold mb-3">Algorithms</h2>
        <v-layout justify-center>
          <v-expansion-panel dark>
            <v-expansion-panel-content
              v-for="(problem, i) in problems"
              :key="i"
            >
              <template v-slot:header >
                <h3>{{problem.title}}</h3>
              </template>
              <v-card>
                <v-card-text>
                  <tt application v-html="problem.description"></tt>
                  <br/>
                  <v-btn
                    light
                    v-on:click="currentPage = 'About'"
                  >
                    <span>Solution</span>
                  </v-btn>
                </v-card-text>
              </v-card>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-layout>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>

export default {
  name: 'Algorithms',
  components: {
  },
  data: () => ({
    colors: [
      'd-blue',
      'l-blue',
      'orange',
      'yellow',
    ],
    problems: [
      {
        title: 'Even Fibonacci Numbers',
        description: '<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:<br/><br/>&nbsp&nbsp&nbsp&nbsp1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br/><br/>Consider the terms in the Fibonacci sequence whose values do not exceed four million find the sum of the even-valued terms.</p>',
      },
      {
        title: 'Number Spiral Diagonals',
        description: '<p>Starting with the number 1 and moving to the r in a clockwise direction a 5 by 5 spiral is formed as follows:<br/><br/>&nbsp&nbsp&nbsp&nbsp43 44 45 46 47 48 49<br/>&nbsp&nbsp&nbsp&nbsp42 21 22 23 24 25 26&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp21 22 23 24 25 26<br/>&nbsp&nbsp&nbsp&nbsp41 20&nbsp&nbsp7&nbsp&nbsp8&nbsp&nbsp9 10 27&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp20&nbsp&nbsp7&nbsp&nbsp8&nbsp&nbsp9 10 27<br/>&nbsp&nbsp&nbsp&nbsp40 19&nbsp&nbsp6&nbsp&nbsp1&nbsp&nbsp2 11 28&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp19&nbsp&nbsp6&nbsp&nbsp1&nbsp&nbsp2 11 28<br/>&nbsp&nbsp&nbsp&nbsp39 18&nbsp&nbsp5&nbsp&nbsp4&nbsp&nbsp3 12 29&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp18&nbsp&nbsp5&nbsp&nbsp4&nbsp&nbsp3 12 29<br/>&nbsp&nbsp&nbsp&nbsp38 17 16 15 14 13 30&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp17 16 15 14 13 30<br/>&nbsp&nbsp&nbsp&nbsp37 36 35 34 33 32 31&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp36 35 34 33 32 31</p><p>It can be verified that the sum of the numbers on the diagonals is 101.</p><p>What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?</p>',
      },
      {
        title: 'Digit cancelling fractions',
        description: '<p>The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.</p><p>We shall consider fractions like, 30/50 = 3/5, to be trivial examples.</p><p>There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.</p><p>If the product of these four fractions is given in its lowest common terms, find the value of the denominator.</p>',
      },
      {
        title: 'Truncatable primes',
        description: '<p>The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage:<br/><br/>&nbsp&nbsp&nbsp&nbsp3797, 797, 97, and 7.<br/><br/>Similarly we can work from right to left:<br/><br/>&nbsp&nbsp&nbsp&nbsp3797, 379, 37, and 3.</p><p>Find the sum of the only eleven primes that are both truncatable from left to right and right to left.</p><p>NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.</p>',
      },
    ],
  }),
  mounted: {

  },
};
</script>
<style scoped>
  .application{
    color: #3c3b3a;
    background: #dacfb3;
  }
  .v-toolbar{
    color: #3c3b3a;
    background: #dacfb3;
  }
  .d-blue{
    background: #0f2343;
    color: #3c3b3a;
  }
  .l-blue{
    background: #21496c;
    color: #3c3b3a;
  }
  .orange{
    background: #db8420;
    color: #3c3b3a;
  }
  .yellow{
    background: #c43912;
    color: #3c3b3a;
  }
  .cream{
    background: #3c3b3a;
  }
</style>
