<template>
  <v-container>
    <v-layout
      text-xs-center
      wrap
    >
      <v-flex
        mb-5
        xs12
      >
        <h2 class="headline font-weight-bold mb-3">Algorithms</h2>
        <v-layout justify-center>
          <v-expansion-panel>
            <v-expansion-panel-content
              v-for="(problem, i) in problems"
              :key="i"
            >
              <template v-slot:header   :class='colors[i%4]'>
                <div>{{problem.title}}</div>
              </template>
              <v-card>
                <v-card-text>
                  <pre>{{problem.description}}</pre>
                </v-card-text>
              </v-card>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-layout>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>

export default {
  name: 'Algorithms',
  components: {
  },
  data: () => ({
    colors: [
      'd-blue',
      'l-blue',
      'orange',
      'yellow',
    ],
    problems: [
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
      {
        title: 'Even Fibonacci Numbers',
        description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nConsider the terms in the Fibonacci sequence whose values do not exceed four million\nfind the sum of the even-valued terms.',
      },
    ],
  }),
  mounted: {

  },
};
</script>

<style>
  .d-blue{
    background: '#db8420';
  }
  .l-blue{
    background: '#0f2343';
  }
  .orange{
    background: '#21496c';
  }
  .yellow{
    background: '#c43912';
  }
  .cream{
    background: '#3c3b3a';
  }
</style>
